"""Measures what the force limit actually buys, and writes docs/admittance-bound.md.

Run with:

    python scripts/admittance_sweep.py

Pure numpy against the closed-loop spring-wall model from tests/test_admittance.py,
so it takes about a second and needs no simulator. The point is to publish the
*measured* behaviour of the bound -- including where the transient exceeds it --
rather than asserting a guarantee the controller does not have.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tests"))

from griff.control import AdmittanceConfig, AdmittanceController  # noqa: E402
from test_admittance import press  # noqa: E402

STIFFNESSES = (400, 800, 1500, 2500, 5000, 10000, 25000, 60000)
RAMP_RATES_MM = (0.2, 0.5, 1.0, 2.0, 4.0)


def table(rows: list[list[str]], header: list[str]) -> str:
    widths = [max(len(header[i]), *(len(r[i]) for r in rows)) for i in range(len(header))]
    out = ["| " + " | ".join(h.ljust(w) for h, w in zip(header, widths, strict=True)) + " |",
           "|" + "|".join("-" * (w + 2) for w in widths) + "|"]
    out += ["| " + " | ".join(c.ljust(w) for c, w in zip(r, widths, strict=True)) + " |"
            for r in rows]
    return "\n".join(out)


def stiffness_sweep() -> tuple[str, float]:
    rows = []
    worst = 0.0
    for stiffness in STIFFNESSES:
        controller = AdmittanceController()
        trace = press(controller, env_stiffness=float(stiffness), ticks=500)
        peak = float(trace["force"].max())
        settled = float(trace["force"][-60:].mean())
        worst = max(worst, peak)
        rows.append([
            f"{stiffness:,}",
            f"{peak:.2f}",
            f"{settled:.2f}",
            f"{peak / controller.config.force_limit:.2f}x",
            f"{controller.state.stiffness:,.0f}",
        ])
    header = ["environment stiffness (N/m)", "peak force (N)", "settled force (N)",
              "peak / limit", "estimated stiffness (N/m)"]
    return table(rows, header), worst


def approach_sweep() -> str:
    rows = []
    for rate_mm in RAMP_RATES_MM:
        # `press` ramps `commanded_depth + start_z` over half the ticks, so the
        # per-tick approach rate is set by choosing the tick count.
        travel = 0.030 + 0.050
        ticks = int(2 * travel / (rate_mm / 1000.0))
        controller = AdmittanceController()
        trace = press(controller, env_stiffness=10000.0, ticks=ticks)
        rows.append([
            f"{rate_mm:.1f}",
            f"{rate_mm * 30 / 10:.1f}",
            f"{trace['force'].max():.2f}",
            f"{trace['force'][-60:].mean():.2f}",
        ])
    return table(
        rows,
        ["approach (mm/tick)", "approach (cm/s)", "peak force (N)", "settled force (N)"],
    )


def limit_sweep() -> str:
    rows = []
    for limit in (3.0, 6.0, 8.0, 12.0):
        controller = AdmittanceController(AdmittanceConfig(force_limit=limit))
        trace = press(controller, env_stiffness=2500.0, ticks=500)
        rows.append([
            f"{limit:.0f}",
            f"{trace['force'].max():.2f}",
            f"{trace['force'][-60:].mean():.2f}",
            f"{controller.state.governed_ticks}",
        ])
    return table(rows, ["configured limit (N)", "peak (N)", "settled (N)", "governed ticks"])


def unguarded_control() -> str:
    """What the same commanded penetration does with the advance cap removed."""
    rows = []
    for stiffness in (1500, 2500, 10000):
        pinned = AdmittanceController(
            AdmittanceConfig(
                stiffness_prior=250.0, stiffness_bounds=(250.0, 250.1), force_limit=1e6
            )
        )
        guarded = AdmittanceController()
        free_peak = press(pinned, env_stiffness=float(stiffness), ticks=500)["force"].max()
        bound_peak = press(guarded, env_stiffness=float(stiffness), ticks=500)["force"].max()
        rows.append([
            f"{stiffness:,}",
            f"{free_peak:.1f}",
            f"{bound_peak:.2f}",
            f"{free_peak / bound_peak:.0f}x",
        ])
    return table(
        rows,
        ["environment stiffness (N/m)", "admittance only (N)", "with the governor (N)",
         "reduction"],
    )


def main() -> None:
    stiffness_table, worst = stiffness_sweep()
    config = AdmittanceConfig()
    document = f"""# What the force limit actually bounds

Generated by `python scripts/admittance_sweep.py`. Numbers are from the
closed-loop spring-wall model in `tests/test_admittance.py`: a
position-commanded arm that tracks its reference exactly, meeting a linear
spring. That is the worst case. A real SO-101 has roughly 850 N/m of its own
servo compliance in series with the environment, which only ever reduces the
force produced by a given command.

In every run below the policy commands 50 mm *into* the wall and holds -- it
asks for something that would destroy the workpiece -- and the controller is
configured with a {config.force_limit:.0f} N limit.

## The claim, precisely

**Steady state is bounded.** In sustained contact the force settles at the
limit, at every environment stiffness tested, however deep the policy commanded.
This is the property the reference governor enforces and it holds by
construction: while the measured force is at the limit the reference may not
advance, and above it the governor commands a retreat sized by the stiffness
estimate.

**The transient is bounded in practice, not by construction.** First contact is
an impact, and impact force is set by approach speed and environment stiffness,
not by feedback -- no controller commanding position at 30 Hz can avoid that.
What the online stiffness estimator does is make the first contact tick
cautious, and the worst overshoot measured across the sweep below is
{worst / config.force_limit:.2f}x the limit.

## Peak and settled force against environment stiffness

{stiffness_table}

The settled column is the bound. The peak column is the impact, and it grows
with stiffness because the first tick of contact happens before there is any
force to react to.

## Approach speed

{approach_sweep()}

Slower approaches produce smaller impacts, which is why
`griff.teleop.operator.Operator.MAX_REFERENCE_RATE` caps the demonstrations at
3.6 cm/s and why `AdmittanceConfig.max_step` caps the controller at
{config.max_step * 30 * 100:.1f} cm/s.

## The limit is a knob that does what its name says

{limit_sweep()}

## Admittance alone does not bound anything

The control experiment. Remove the advance cap -- leave the virtual
mass-damper-spring, remove the governor -- and the same commanded penetration
produces:

{unguarded_control()}

This is why the controller has three mechanisms and not one. Compliance softens
contact; only the governor bounds it.

## What this does not cover

* The bound is stated against the **estimated** force, and the estimate carries
  1-2 N of error in the operating range (see `docs/force-estimation.md`). The
  ground-truth force corresponding to a {config.force_limit:.0f} N limit is
  therefore {config.force_limit:.0f} N plus that error, which is why every task's
  overload threshold sits above its controller limit.
* Nothing here has run on hardware. The C++ port in
  `ros2_ws/src/griff_control` asserts these same properties in its own gtest
  suite, so the two implementations are checked against each other, but neither
  has met a real servo.
"""
    out = Path(__file__).resolve().parent.parent / "docs" / "admittance-bound.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(document, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
