"""Renders results/RESULTS.md from results/results.json.

RESULTS.md is generated, never hand-written, and CI checks that regenerating it
produces no diff. That is the only way a results file stays honest across a
year of edits: the alternative is a table that was true when it was pasted in.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from griff.paths import RESULTS
from griff.sim.tasks import SPECS

CONDITIONING_LABEL = {
    "vision": "vision only",
    "vision_zeroforce": "vision + blinded force",
    "vision_force": "vision + force",
    "scripted": "scripted operator",
}


def _table(rows: list[list[str]], header: list[str]) -> str:
    widths = [max(len(header[i]), *(len(row[i]) for row in rows)) if rows else len(header[i])
              for i in range(len(header))]
    lines = [
        "| " + " | ".join(h.ljust(w) for h, w in zip(header, widths, strict=True)) + " |",
        "|" + "|".join("-" * (w + 2) for w in widths) + "|",
    ]
    lines += [
        "| " + " | ".join(cell.ljust(w) for cell, w in zip(row, widths, strict=True)) + " |"
        for row in rows
    ]
    return "\n".join(lines)


def _rate(value: float, interval: list[float] | tuple[float, float]) -> str:
    return f"{value * 100:.0f}% ({interval[0] * 100:.0f}-{interval[1] * 100:.0f})"


def _key(evaluation: dict[str, Any]) -> tuple[str, str]:
    return evaluation["policy"], evaluation["conditioning"]


def render(payload: dict[str, Any]) -> str:
    parts: list[str] = []
    parts.append("# Results\n")
    parts.append(
        "Generated by `griff report` from `results/results.json`. Do not edit by hand -- "
        "CI regenerates this file and fails on a diff.\n"
    )
    parts.append(
        "Every policy meets the same episode seeds, so comparisons within a task are paired. "
        "Rates carry 95% Wilson intervals. **Peak force is read from the simulator's "
        "ground-truth F/T sensor**, not from the servo-load estimate the policy and the "
        "controller actually run on -- grading a safety property with the same noisy signal "
        "the system used to try to satisfy it would let estimator error hide the failures "
        "being looked for.\n"
    )

    parts.append("## Scoring\n")
    parts.append(
        "**Task success** is the task's own criterion: peg inserted, plate wiped end to end, "
        "part seated. **Force-aware success** additionally requires that peak contact force "
        "stayed below the threshold at which the workpiece is considered damaged. A run that "
        "completes the task by crushing the part counts as a failure, because on real hardware "
        "it is one.\n"
    )

    thresholds = [
        [task, f"{spec.overload_force:.0f} N", f"{spec.force_limit:.0f} N", spec.description]
        for task, spec in SPECS.items()
    ]
    parts.append(
        _table(thresholds, ["task", "overload threshold", "controller limit", "goal"]) + "\n"
    )

    for task, evaluations in payload["tasks"].items():
        spec = SPECS[task]
        parts.append(f"## {task}\n")
        guarded = [e for e in evaluations if e["guarded"]]
        unguarded = {_key(e): e for e in evaluations if not e["guarded"]}

        rows = []
        for evaluation in guarded:
            label = CONDITIONING_LABEL.get(evaluation["conditioning"], evaluation["conditioning"])
            rows.append([
                f"{evaluation['policy']} / {label}",
                _rate(evaluation["task_success_rate"], evaluation["task_success_ci"]),
                _rate(
                    evaluation["force_aware_success_rate"], evaluation["force_aware_success_ci"]
                ),
                f"{evaluation['peak_force_mean_n']:.1f}",
                f"{evaluation['peak_force_p95_n']:.1f}",
                f"{evaluation['peak_force_max_n']:.1f}",
                f"{evaluation['overload_rate'] * 100:.0f}%",
            ])
        parts.append(
            _table(
                rows,
                [
                    "policy / conditioning",
                    "task success",
                    "force-aware success",
                    "peak F mean",
                    "p95",
                    "max",
                    "overload",
                ],
            )
            + "\n"
        )
        if guarded:
            parts.append(
                f"All rows above ran behind the force-limited admittance controller at a "
                f"{spec.force_limit:.0f} N limit, over {guarded[0]['episodes']} episodes each. "
                f"Peak force is the simulator's ground truth; the controller and the policies "
                f"both ran on the servo-load estimate.\n"
            )

        # --- the force ablation, with capacity held fixed ---
        ablation = []
        for policy in ("act", "diffusion"):
            blind = next(
                (e for e in guarded if _key(e) == (policy, "vision_zeroforce")), None
            )
            sighted = next((e for e in guarded if _key(e) == (policy, "vision_force")), None)
            plain = next((e for e in guarded if _key(e) == (policy, "vision")), None)
            if not (blind and sighted):
                continue
            delta = sighted["force_aware_success_rate"] - blind["force_aware_success_rate"]
            capacity = (
                blind["force_aware_success_rate"] - plain["force_aware_success_rate"]
                if plain
                else float("nan")
            )
            ablation.append([
                policy,
                f"{plain['force_aware_success_rate'] * 100:.0f}%" if plain else "-",
                f"{blind['force_aware_success_rate'] * 100:.0f}%",
                f"{sighted['force_aware_success_rate'] * 100:.0f}%",
                f"{delta * 100:+.0f} pp",
                f"{capacity * 100:+.0f} pp",
            ])
        if ablation:
            parts.append("### What the force channel contributes\n")
            parts.append(
                _table(
                    ablation,
                    [
                        "policy",
                        "vision",
                        "blinded force",
                        "force",
                        "information (force - blinded)",
                        "capacity (blinded - vision)",
                    ],
                )
                + "\n"
            )
            parts.append(
                "The blinded arm has the force branch and its parameters but is fed a constant "
                "zero, so the *information* column isolates what the signal contributes with "
                "capacity held fixed, and the *capacity* column shows what those parameters buy "
                "on their own.\n"
            )

        # --- what the controller costs and buys ---
        if unguarded:
            rows = []
            for evaluation in guarded:
                free = unguarded.get(_key(evaluation))
                if not free:
                    continue
                label = CONDITIONING_LABEL.get(
                    evaluation["conditioning"], evaluation["conditioning"]
                )
                rows.append([
                    f"{evaluation['policy']} / {label}",
                    f"{free['task_success_rate'] * 100:.0f}%",
                    f"{evaluation['task_success_rate'] * 100:.0f}%",
                    f"{free['peak_force_max_n']:.1f}",
                    f"{evaluation['peak_force_max_n']:.1f}",
                    f"{free['overload_rate'] * 100:.0f}%",
                    f"{evaluation['overload_rate'] * 100:.0f}%",
                ])
            if rows:
                parts.append("### With and without the admittance guard\n")
                parts.append(
                    "Only the force-conditioned arm is run twice. The guard's effect is a "
                    "property of the controller rather than of the conditioning, and the "
                    "force-conditioned policy is the one that could in principle have "
                    "learned to limit its own contact -- so it is the interesting one to "
                    "take the guard away from.\n"
                )
                parts.append(
                    _table(
                        rows,
                        [
                            "policy / conditioning",
                            "task success (free)",
                            "(guarded)",
                            "peak F max (free)",
                            "(guarded)",
                            "overload (free)",
                            "(guarded)",
                        ],
                    )
                    + "\n"
                )

    parts.append("## Reproducing\n")
    parts.append(
        "```console\n"
        "$ griff reproduce\n"
        "```\n\n"
        "Or the steps separately: `griff calibrate`, `griff record`, `griff train-grid`, "
        "`griff evaluate`. Episode seeds are fixed and committed; the datasets, configs and "
        "seeds needed to reproduce every number here are in the repository.\n"
    )
    return "\n".join(parts)


def write_report(results: Path | None = None, out: Path | None = None) -> Path:
    results = results or RESULTS / "results.json"
    out = out or RESULTS / "RESULTS.md"
    payload = json.loads(results.read_text(encoding="utf-8-sig"))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(payload), encoding="utf-8")
    return out
